#!/bin/bash

UILDROOTCONIFGNEW="`pwd`/config.default"

DEBUG="no"
VERBOSE="no"

function fail 
{
    msg=$1
    echo "[F] $msg"
    echo "FAIL AND EXITING"
    exit 42
}

function debug
{
    if [ "x$DEBUG" == "xyes" ] ;  then
        msg=$1
        echo "[D] $msg"
    fi
}

function debug_pause
{
    if [ "x$DEBUG" == "xyes" ] ;  then
        msg=$1
        echo "[D] $msg"
        read -p"<press enter to roll forward>"
    fi
}

function verbose
{
    if [ "x$VERBOSE" == "xyes" ] ;  then
        msg=$1
        echo "[V] $msg"
    fi
}

function info
{
    msg=$1
    echo "[*] $msg"
}

function cleanup
{
    rm -v $OPTBUILDDIR

    if [ "$ARCH" != "" ] && [ -d $OPTGCCARCH ]
    then
        ls $OPTGCCARCH | grep -v host | xargs -i rm -rf $OPTGCCARCH/{}
    fi
}

